backend:
  name: github
  repo: Tn1ck/tomnick.org
  branch: netlify-test # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "Single Pages" # Used in routes, e.g., /admin/collections/blog
    label: "single_pages" # Used in the UI
    files:
      - label: "about"
        name: "About"
        file: 'content/about/about.md'
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
